## Dataset Understanding

Your work should include:

- Number of rows and columns
- Type of input features
- Target variable description
- Missing value check
- Basic statistical summary
- Distribution of the target variable

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("customer_churn_nn.csv")
df.shape

(2000, 17)

In [ ]:
df.head()

,customer_id,region,plan_type,contract_type,payment_method,tenure_months,monthly_charges_inr,avg_login_days_per_month,support_tickets_last_90_days,payment_delay_days,data_usage_gb,satisfaction_score,last_complaint_days_ago,discount_percent,autopay_enabled,referral_count,churn
0,CUST0001,South,Standard,Month-to-month,Debit Card,30,687.40,13,0,0,87.97,8.0,67,0,0,0,0
1,CUST0002,West,Premium,Month-to-month,Wallet,15,1029.74,22,3,1,82.17,5.7,69,0,0,0,0
2,CUST0003,Central,Standard,Month-to-month,Credit Card,72,732.07,13,0,11,89.39,6.4,63,10,0,0,0
3,CUST0004,West,Premium,Month-to-month,Credit Card,22,959.51,19,2,3,139.73,7.2,130,5,0,0,0
4,CUST0005,North,Premium,Month-to-month,Net Banking,11,890.20,18,2,6,156.43,5.8,0,5,1,2,0

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   2000 non-null   str
 1   region                        2000 non-null   str
 2   plan_type                     2000 non-null   str
 3   contract_type                 2000 non-null   str
 4   payment_method                2000 non-null   str
 5   tenure_months                 2000 non-null   int64
 6   monthly_charges_inr           2000 non-null   float64
 7   avg_login_days_per_month      2000 non-null   int64
 8   support_tickets_last_90_days  2000 non-null   int64
 9   payment_delay_days            2000 non-null   int64
 10  data_usage_gb                 2000 non-null   float64
 11  satisfaction_score            2000 non-null   float64
 12  last_complaint_days_ago       2000 non-null   int64
 13  discount_percent              2000 non-null   int64
 14  autopay_enabled               2000 non-null   int64
 15  referral_count                2000 non-null   int64
 16  churn                         2000 non-null   int64
dtypes: float64(3), int64(9), str(5)
memory usage: 265.8 KB

In [ ]:
round(df.describe(),2)

,tenure_months,monthly_charges_inr,avg_login_days_per_month,support_tickets_last_90_days,payment_delay_days,data_usage_gb,satisfaction_score,last_complaint_days_ago,discount_percent,autopay_enabled,referral_count,churn
count,2000.00,2000.00,2000.0,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00
mean,25.36,766.49,18.1,1.95,3.56,90.01,6.87,46.62,8.26,0.60,0.92,0.02
std,14.13,393.42,5.4,1.46,3.89,53.22,1.52,55.07,7.55,0.49,1.04,0.12
min,1.00,255.45,0.0,0.00,0.00,0.50,1.00,0.00,0.00,0.00,0.00,0.00
25%,15.00,427.78,15.0,1.00,1.00,51.78,5.88,6.00,0.00,0.00,0.00,0.00
50%,23.00,688.36,18.0,2.00,2.00,80.24,6.80,28.50,5.00,1.00,1.00,0.00
75%,33.00,1007.37,22.0,3.00,5.00,119.10,8.00,68.00,15.00,1.00,1.00,0.00
max,72.00,2156.52,30.0,8.00,31.00,265.51,10.00,424.00,20.00,1.00,7.00,1.00

In [ ]:
print(df.nunique())

customer_id                     2000
region                             5
plan_type                          4
contract_type                      3
payment_method                     5
tenure_months                     72
monthly_charges_inr             1976
avg_login_days_per_month          30
support_tickets_last_90_days       9
payment_delay_days                26
data_usage_gb                   1877
satisfaction_score                79
last_complaint_days_ago          222
discount_percent                   5
autopay_enabled                    2
referral_count                     8
churn                              2
dtype: int64

In [ ]:
df['region'].unique()

<StringArray>
['South', 'West', 'Central', 'North', 'East']
Length: 5, dtype: str

In [ ]:
df['plan_type'].unique()

<StringArray>
['Standard', 'Premium', 'Basic', 'Enterprise']
Length: 4, dtype: str

In [ ]:
df['contract_type'].unique()

<StringArray>
['Month-to-month', 'One-year', 'Two-year']
Length: 3, dtype: str

In [ ]:
df['payment_method'].unique()

<StringArray>
['Debit Card', 'Wallet', 'Credit Card', 'Net Banking', 'UPI']
Length: 5, dtype: str

### creating a convunutional neural network

#### part 1 changing dtypes and standardizing the data

In [ ]:
df.head()

,customer_id,region,plan_type,contract_type,payment_method,tenure_months,monthly_charges_inr,avg_login_days_per_month,support_tickets_last_90_days,payment_delay_days,data_usage_gb,satisfaction_score,last_complaint_days_ago,discount_percent,autopay_enabled,referral_count,churn
0,CUST0001,South,Standard,Month-to-month,Debit Card,30,687.40,13,0,0,87.97,8.0,67,0,0,0,0
1,CUST0002,West,Premium,Month-to-month,Wallet,15,1029.74,22,3,1,82.17,5.7,69,0,0,0,0
2,CUST0003,Central,Standard,Month-to-month,Credit Card,72,732.07,13,0,11,89.39,6.4,63,10,0,0,0
3,CUST0004,West,Premium,Month-to-month,Credit Card,22,959.51,19,2,3,139.73,7.2,130,5,0,0,0
4,CUST0005,North,Premium,Month-to-month,Net Banking,11,890.20,18,2,6,156.43,5.8,0,5,1,2,0

In [ ]:
df.columns

Index(['customer_id', 'region', 'plan_type', 'contract_type', 'payment_method',
       'tenure_months', 'monthly_charges_inr', 'avg_login_days_per_month',
       'support_tickets_last_90_days', 'payment_delay_days', 'data_usage_gb',
       'satisfaction_score', 'last_complaint_days_ago', 'discount_percent',
       'autopay_enabled', 'referral_count', 'churn'],
      dtype='str')

In [ ]:
# maping str to int
df['region'] = df['region'].map({'South': 0, 'West': 1, 'Central': 2, 'North': 3, 'East': 4})
df['plan_type'] = df['plan_type'].map({'Basic': 0, 'Standard': 1, 'Premium': 2, 'Enterprise':3})
df['contract_type'] = df['contract_type'].map({'Month-to-month': 0, 'One-year': 1, 'Two-year': 2})
df['payment_method'] = df['payment_method'].map({'Debit Card': 0, 'Wallet': 1, 'Credit Card': 2, 'Net Banking': 3, 'UPI': 4})
df.head()

,customer_id,region,plan_type,contract_type,payment_method,tenure_months,monthly_charges_inr,avg_login_days_per_month,support_tickets_last_90_days,payment_delay_days,data_usage_gb,satisfaction_score,last_complaint_days_ago,discount_percent,autopay_enabled,referral_count,churn
0,CUST0001,0,1,0,0,30,687.40,13,0,0,87.97,8.0,67,0,0,0,0
1,CUST0002,1,2,0,1,15,1029.74,22,3,1,82.17,5.7,69,0,0,0,0
2,CUST0003,2,1,0,2,72,732.07,13,0,11,89.39,6.4,63,10,0,0,0
3,CUST0004,1,2,0,2,22,959.51,19,2,3,139.73,7.2,130,5,0,0,0
4,CUST0005,3,2,0,3,11,890.20,18,2,6,156.43,5.8,0,5,1,2,0

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   2000 non-null   str
 1   region                        2000 non-null   int64
 2   plan_type                     2000 non-null   int64
 3   contract_type                 2000 non-null   int64
 4   payment_method                2000 non-null   int64
 5   tenure_months                 2000 non-null   int64
 6   monthly_charges_inr           2000 non-null   float64
 7   avg_login_days_per_month      2000 non-null   int64
 8   support_tickets_last_90_days  2000 non-null   int64
 9   payment_delay_days            2000 non-null   int64
 10  data_usage_gb                 2000 non-null   float64
 11  satisfaction_score            2000 non-null   float64
 12  last_complaint_days_ago       2000 non-null   int64
 13  discount_percent              2000 non-null   int64
 14  autopay_enabled               2000 non-null   int64
 15  referral_count                2000 non-null   int64
 16  churn                         2000 non-null   int64
dtypes: float64(3), int64(13), str(1)
memory usage: 265.8 KB

In [ ]:
df.head()

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
columns = ['tenure_months', 'monthly_charges', 'total_charges']
df[columns] = scaler.fit_transform(df[columns])
df.head()

In [ ]:
from sklearn.model_selection import train_test_split
x = df.drop('churn', axis=1)
y = df['churn']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.shape, y_train.shape)